EmployeeManagement/ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        public string RoleName { get; set; }
    }

}

EmployeeManagement/ViewModels/EditRoleViewModel.cs
using EmployeeManagement.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.ViewModels
{
    public class EditRoleViewModel
    {
        public EditRoleViewModel()
        {
            //Kudvenkat's code
            //Users = new List<string>();
        }
        public string Id { get; set; }
        [Required]
        public string RoleName { get; set; }
        public List<string> Users { get; set; } = new List<string>(); //Netizen suggest in C# version lastest: instantial object
    }
}

EmployeeManagement/ViewModels/EditUserViewModel.cs
using EmployeeManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EmployeeManagement.ViewModels
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string City { get; set; }
        public IList<string> Roles { get; set; }
        public IList<string> Claims { get; set; }
    }
}

EmployeeManagement/Controllers/AdministrationController.cs
using EmployeeManagement.Models;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole
                {
                    Name = model.RoleName
                };
                var result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            return View(roleManager.Roles);
        }


        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"The Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = id,
                RoleName = role.Name,
            };

            //Kudvenkat's code does: it works, by set Multiple Active Result (MARS) in connectionString to true or ToList() userManager.Users
            //foreach (var user in userManager.Users)
            //{
            //    if (await userManager.IsInRoleAsync(user, role.Name))
            //    {
            //        model.Users.Add(user.UserName);
            //    }
            //}

            //Netizen's code does :D
            IList<ApplicationUser> listUsers = await userManager.GetUsersInRoleAsync(role.Name);
            foreach (var item in listUsers)
            {
                model.Users.Add(item.UserName);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"The Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }

            role.Name = model.RoleName;

            var result = await roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("ListRoles");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"The Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            List<UserRoleViewModel> model = new List<UserRoleViewModel>();
            foreach (var user in userManager.Users)
            {
                UserRoleViewModel item = new UserRoleViewModel();
                item.UserId = user.Id;
                item.UserName = user.UserName;
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    item.IsSelected = true;
                }
                else
                {
                    item.IsSelected = false;
                }

                model.Add(item);
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"The Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }
            IdentityResult result = new IdentityResult();
            foreach (var item in model)
            {

                ApplicationUser user = await userManager.FindByIdAsync(item.UserId);
                bool status = await userManager.IsInRoleAsync(user, role.Name);
                if (item.IsSelected && !status)
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!item.IsSelected && status)
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }
            }

            //for (int i = 0; i< model.Count; i++)
            //{
            //    IdentityResult result = new IdentityResult();
            //    ApplicationUser user = await userManager.FindByIdAsync(model[i].UserId);

            //    if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
            //    {
            //        result = await userManager.AddToRoleAsync(user, role.Name);
            //    }
            //    else if (!model[i].IsSelected && (await userManager.IsInRoleAsync(user, role.Name)))
            //    {
            //        result = await userManager.RemoveFromRoleAsync(user, role.Name);
            //    }
            //    else
            //    {
            //        continue;
            //    }
            //    if (result.Succeeded)
            //    {
            //        if (i<(model.Count-1))
            //        {
            //            continue;   
            //        }
            //        else
            //        {
            //            return RedirectToAction("EditRole", new {id = roleId});
            //        }
            //    }
            //}

            return RedirectToAction("EditRole", new { id = roleId });
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            return View(userManager.Users);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"The User with Id = {id} cannot be found";
                return View("NotFound");
            }

            var userRoles = await userManager.GetRolesAsync(user);
            var userClaims = await userManager.GetClaimsAsync(user);

            EditUserViewModel model = new EditUserViewModel();
            model.Id = user.Id;
            model.Email = user.Email;
            model.UserName = user.UserName;
            model.City = user.City;
            model.Roles = userRoles;
            model.Claims = userClaims.Select(x => x.Value).ToList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"The User with Id = {model.Id} cannot be found";
                return View("NotFound");
            }

            user.Email = model.Email;
            user.UserName = model.UserName;
            user.City = model.City;

            var result = await userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction("ListUsers");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(model);
        }
    }
}

EmployeeManagement/Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewBag.PageTitle = "Create Role";
}

<div class="col-lg-6">
    <form method="post">
        <h3>Create Role</h3>
        <div class="mb-3">
            <label asp-for="RoleName" class="form-label">Role Name</label>
            <input asp-for="RoleName" class="form-control">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>

        <button type="submit" class="btn btn-primary" style="width:auto">Create Role</button>
    </form>
</div>

EmployeeManagement/Views/Administration/EditRole.cshtml
@model EditRoleViewModel
@{
    ViewBag.Title = "Edit Role";
}

<div class="mt-3">
    <form method="post">
        <h3>Edit Role</h3>
        <div class="mb-3 row">
            <label asp-for="Id" class="col-sm-1 col-form-label">Id</label>
            <div class="col-sm-11">
                <input asp-for="Id" readonly class="form-control">
            </div>
        </div>
        <div class="mb-3 row">
            <label asp-for="RoleName" class="col-sm-1 col-form-label">Role Name</label>
            <div class="col-sm-11">
                <input asp-for="RoleName" class="form-control">
            </div>
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>

        <button type="submit" class="btn btn-primary" style="width:auto">Update</button>
        <a class="btn btn-primary" asp-action="ListRoles">Cancel</a>
    </form>
</div>


<div class="mt-3">

    <div class="card mb-3">
        <div class="card-header">
            <h5>Users in this role</h5>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                @foreach (var user in Model.Users)
                {
                    <h3 class="card-title">@user</h3>
                }
            }
            else
            {
                <h5 class="card-title">There is not any user in this role</h5>
            }
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" style="width:auto">Add or Remove User From Role</a>
        </div>
    </div>
</div>

EmployeeManagement/Views/Administration/EditUser.cshtml
@model EditUserViewModel

@{
    ViewBag.PageTitle = "Edit User";
}

<form method="post">
    <h3>Edit User</h3>
    <div class="mb-3 row">
        <label asp-for="Id" class="col-sm-1 col-form-label">Id</label>
        <div class="col-sm-11">
            <input asp-for="Id" readonly class="form-control">
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="Email" class="col-sm-1 col-form-label">Email</label>
        <div class="col-sm-11">
            <input asp-for="Email" class="form-control">
        </div>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3 row">
        <label asp-for="UserName" class="col-sm-1 col-form-label">User Name</label>
        <div class="col-sm-11">
            <input asp-for="UserName" class="form-control">
        </div>
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>
    <div class="mb-3 row">
        <label asp-for="City" class="col-sm-1 col-form-label">City</label>
        <div class="col-sm-11">
            <input asp-for="City" class="form-control">
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>

    <button type="submit" class="btn btn-primary">Update</button>
    <a class="btn btn-primary" asp-action="ListUsers">Cancel</a>
</form>

<div class="mt-3">
    <div class="card mb-3">
        <div class="card-header">
            <h5>User Roles</h5>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                @foreach (var role in Model.Roles)
                {
                    <h3 class="card-title">@role</h3>
                }
            }
            else
            {
                <h5 class="card-title">There is not any role in this user</h5>
            }
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" asp-action="ManageRoles" asp-controller="Administration" asp-route-roleId="@Model.Id" style="width:auto">Manage Roles</a>
        </div>
    </div>
</div>

<div class="mt-3">
    <div class="card mb-3">
        <div class="card-header">
            <h5>User Claims</h5>
        </div>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                @foreach (var claim in Model.Claims)
                {
                    <h3 class="card-title">@claim</h3>
                }
            }
            else
            {
                <h5 class="card-title">There is not any claim in this user</h5>
            }
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" asp-action="ManageClaims" asp-controller="Administration" asp-route-roleId="@Model.Id" style="width:auto">Manage Claims</a>
        </div>
    </div>
</div>

EmployeeManagement/Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    ViewBag.Title = "Edit Users In Role";
    var roleId = ViewBag.RoleId;
}

<div class="mt-3">
    <form method="post">
        <div class="card mb-3">
            <div class="card-header">
                <h5>Edit Users In Role</h5>
            </div>
            <div class="card-body">

                @for (int i = 0; i < Model.Count; i++)
                {
                    <input hidden asp-for="@Model[i].UserId" />
                    <input hidden asp-for="@Model[i].UserName" />
                    <div class="form-check m-1">
                        <input class="form-check-input" asp-for="@Model[i].IsSelected">
                        <label class="form-check-label" asp-for="@Model[i].IsSelected">
                            @Model[i].UserName
                        </label>
                    </div>
                }
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" style="width:auto">Update</button>
                <a class="btn btn-primary" asp-route-id="@roleId" asp-action="EditRole">Cancel</a>
            </div>
        </div>
    </form>
</div>

EmployeeManagement/Views/Administration/ListRoles.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>

@{
    ViewBag.PageTitle = "Create Role";
}

<h1>List Roles</h1>

@if (Model.Any())
{
    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                <h5>Role ID: @role.Id</h5>
            </div>
            <div class="card-body">
                <h3>@role.Name</h3>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" asp-action="EditRole" asp-controller="Administration" asp-route-id="@role.Id" style="width:auto">Edit</a>
                <a class="btn btn-primary" asp-action="DeleteRole" asp-controller="Administration" style="width:auto">Delete</a>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            <h3>There is no role in List Roles</h3>
        </div>
        <div class="card-body">
            <h5>Please click Create Role to add more role to the list</h5>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" asp-action="CreateRole" asp-controller="Administration" style="width:auto">Create Role</a>
        </div>
    </div>
}

EmployeeManagement/Views/Administration/ListUsers.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.PageTitle = "List Users";
}

<h1>List All Users</h1>
<div class="py-3">
    <a class="btn btn-primary" asp-action="Register" asp-controller="Account" style="width:auto">Register</a>
</div>
     
@if (Model.Any())
{
    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                <h5>Role ID: @user.Id</h5>
            </div>
            <div class="card-body">
                <h3>@user.Email</h3>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" asp-action="EditUser" asp-controller="Administration" asp-route-id="@user.Id" style="width:auto">Edit</a>
                <a class="btn btn-primary" asp-action="DeleteUser" asp-controller="Administration" style="width:auto">Delete</a>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            <h3>There is no user in List Users</h3>
        </div>
        <div class="card-body">
            <h5>Please click Register to add more user into the list</h5>
        </div>
        <div class="card-footer">
            
        </div>
    </div>
}